use derive_more::Display;
use serde::{Deserialize, Serialize};
use specta::Type;

/// Serializes to a stable `{ code, data }` wire shape; `code` is the variant
/// name verbatim (generated by the serde attribute - no mapping table to
/// drift). Display is developer-log-only and never crosses the wire (§7g).
#[derive(Type, Serialize, Deserialize, Debug, Display, Clone)]
#[serde(tag = "code", content = "data")]
pub enum SError {
    UnsupportedSPTVersion(String),
    ParseError(String),
    IOError(String),
    GameOrServerRunning,
    ProcessRunning,
    UnableToDetermineModId,
    #[display("Mod not found: {}", _0)]
    ModNotFound(String),
    FileOrDirectoryNotFound(String),
    #[display("File collisions detected: {}", "_0.join(\", \")")]
    FileCollision(Vec<String>),
    Unexpected,
    UnhandledCompression(String),
    AsyncRuntimeError(String),
    NoActiveLibrary,
    #[display("Invalid library at {}: {}", _0, _1)]
    InvalidLibrary(String, String),
    #[display(
        "Mod ID conflict: folder '{}' should be '{}' but target exists",
        _0,
        _1
    )]
    ModIdConflict(String, String),
    #[display("Failed to save app config: {}", _0)]
    ConfigSaveFailed(String),
    #[display("Task id already in flight: {}", _0)]
    TaskIdInUse(String),
}

macro_rules! impl_from {
    ($from_type:ty, $variant:ident) => {
        impl From<$from_type> for SError {
            fn from(err: $from_type) -> Self {
                // We convert the foreign error to a String immediately
                // so we can serialize it later.
                SError::$variant(err.to_string())
            }
        }
    };
}

impl_from!(semver::Error, ParseError);
impl_from!(std::io::Error, IOError);
impl_from!(serde_json::Error, ParseError);
impl_from!(std::path::StripPrefixError, ParseError);
impl_from!(zip::result::ZipError, UnhandledCompression);
